### ISSUE TITLE
🚀 能改成docker不，我想在本地的nas运行，感谢感谢！！！

### ISSUE THREAD

**Issue by JusKyle** [lalifeier/IPTV#2]
### 🚀 Feature Description

1、打包成docker镜像，方便本地部署
2、可通过配置文件，设定是否输出直播源、组播源、酒店源
3、对于组播源、酒店源，可选择运营商、省份

**Comment by lalifeier** [comment]
谢谢你的需求提议！目前我没有空处理这个问题，但欢迎你提交PR。我会在合并后进行审查。感谢你的理解！
