### ISSUE TITLE
你好，大佬！

### ISSUE THREAD

**Issue by zzj2678** [lalifeier/IPTV#3]
### 🐛 Describe the bug

你好，大佬！

### 🌐 Network Environment

你好，大佬！

### 📺 Player

你好，大佬！我复刻了你的这个项目，为啥我启用工作流程都是报错啊！只能同步你的，不能实现自动更新吗？

**Comment by lalifeier** [comment]
报错日志发一下

**Comment by zzj2678** [comment]
还是只启动Auto Update IPTV 这一个工作流？

**Comment by lalifeier** [comment]
除了Auto Update EPG不用启用  其他 Auto Update开头的都要启动

**Comment by zzj2678** [comment]
启动Auto Update IPTV后报错了，Error: Process completed with exit code 1.

**Comment by zzj2678** [comment]
方便加一下QQ吗？大佬

**Comment by zzj2678** [comment]
目前启动了Auto Update IPTV后报错了，其它的还没有启动

**Comment by zzj2678** [comment]
方便加一下QQ吗？大佬

**Comment by lalifeier** [comment]
拉一下最新代码

**Comment by zzj2678** [comment]
好的，我试一下

**Comment by zzj2678** [comment]
代码拉好了，我现在再执行工作流试一下，看报错不，对了，自动更新的时间是每天的什么时候啊？

**Comment by lalifeier** [comment]
更新频率要自己看代码  每个脚本执行时间不一样

**Comment by zzj2678** [comment]
我看了一下是每天的 8:05 AM 和 4:05 PM 运行任务。

**Comment by zzj2678** [comment]
是的，我看了一下，每个工作流执行的时间都不一样

**Comment by zzj2678** [comment]
你那里有一个init的工作流是什么？我这里怎么没有这个？

**Comment by lalifeier** [comment]
你指的是哪里

**Comment by zzj2678** [comment]
就是手动执行工作流那里，我看到你那里有个init的

**Comment by zzj2678** [comment]
可以加一下老师的QQ吗？这样交流有点不方便

**Comment by lalifeier** [comment]
不用QQ 有问题可以在这上面描述清楚

**Comment by zzj2678** [comment]
好的，大佬，刚才拉了一下代码，其它的工作流运行都完成了，没有报错，还剩下一个在运行。

**Comment by zzj2678** [comment]
都运行完毕了，且没有报错，感谢大佬，有问题向您反馈！

**Comment by lalifeier** [comment]
那我先关闭问题，有问题再反馈
